### ISSUE TITLE
Speaker images drop off when url is missing /

### ISSUE THREAD

**Issue by GijsWeterings** [WISVCH/symposium#125] opened 2017-04-29 20:28 UTC
https://symposium.ch.tudelft.nl/2017/speakers vs https://symposium.ch.tudelft.nl/2017/speakers/

This occurs when going from the program to the speakers by clicking on one of the talks. Adding the / and refreshing once more to defeat sw (I presume) brings back the images

**Comment by TimvdLippe** [comment] 2017-04-29 20:29
Could you add repo steps to show how you landed on the url without trailing slash? I cant seem to be able to reproduce it.

**Comment by GijsWeterings** [comment] 2017-04-29 20:30
Upon trying again I found the exact usecase:

1. Go to https://symposium.ch.tudelft.nl/2017/program/
2. Middle click on one of the talks to navigate to the new page in a second tab (this is critical)
3. On the new tab, the images are gone

seems to be a server render vs client-side navigation issue

**Comment by martijnjanssen** [comment] 2017-04-29 20:32
True, the images are missing because it can't load the page itself. Instead it renders the placeholder html in the prerendered index.html for that page.

**Comment by TimvdLippe** [comment] 2017-04-29 20:33
Ah I see. The trailing slashes are missing in the program source indeed.
Seems like an easy fix, mind want to contribute a PR?

**Closed as completed** 2017-04-30 19:40 UTC
